# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Daniel Liu
email: idaniel.liu@gmail.com
# description: > # this means to ignore newlines until "baseurl:"
description: Software engineer, web developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://danielliu.me" # the base hostname & protocol for your site

permalink: /blog/:year/:month/:day/:title/
timezone: America/Los_Angeles
sass:
  style: compressed

# Connections
# twitter_username: djsnoops
github_username: danieliu
linkedin_username: idanielliu
# instagram_username: danieliu
# facebook_username: danieliu


# Serving
port: 4000
host: 0.0.0.0

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman